### ISSUE TITLE
The following modules are missing or built with a different engine version

### ISSUE THREAD

**Issue by Soldream0** [stkrwork/UE-Live2D#1]
The following modules are missing or built with a different engine version:
Live20
Live2DEditor
Live2DModelEdltor
Lwe2DMotionEditor
Would you like to rebuild them now?

>YES

First03(name my project) could not be compiled. Try rebuilding from source manually.

UE 4.27.2
[First03.log](https://github.com/stkrwork/UE-Live2D/files/9896338/First03.log)

p.s. I solved the problem using the function that is called by the right mouse button on the project file "Generate Visual Studio Project files". But now I have another problem? When starting the project, a menu pops up with a warning "Failed to load example third party library", but the project opens. What does this mean?

**Comment by stkrwork** [comment]
It failed to load the native sdk.

Make sure you have added the dll file for Windows x86_64 from the Native SDK to \<plugin root folder containing the uplugin file\>/Binaries/ThirdParty/Live2DLibrary/Win64

So in the end in that folder there should be the file Live2DCubismCore.dll

**Comment by Soldream0** [comment]
See, I open the sdk folder:
CubismSdkForNative-4-r.5.1\Core\dll\windows\x86_64
I copy the file "Live2DCubismCore.dll"

Then...

I open the folder with your plugin and copy the file along the path:
Plugins\UE-Live2D-main\Source\ThirdParty\Live2DLibrary\Win64

Right? I'm sorry for my ignorance, but I can't find the path you suggested, and "plugin root folder containing the uplugin file" I don't know where.

**Comment by stkrwork** [comment]
In your case the folder would be Plugins\UE-Live2D-main\Binaries/ThirdParty/Live2DLibrary/Win64. If it doesnt exist yet, you need to add it.

**Comment by Soldream0** [comment]
Yes, now everything is fine, now it works.
Thanks for the help and thanks for the plugin.

Can you help me with a little hint, where do I start in order to understand how to use your plugin? I'm a bit of a noob, but I'm going to put a lot of emphasis on live2d, whatever the cost.

**Comment by stkrwork** [comment]
Happy to hear that it works.

You can use it in combination with the UMG Images, so once you have set up a widget you can call SetBrushFromLive2DModelMotion in the graph of the widget to make it visible. More details on that is on the bottom of the ReadMe file

**Comment by Soldream0** [comment]
> Happy to hear that it works.
> 
> You can use it in combination with the UMG Images, so once you have set up a widget you can call SetBrushFromLive2DModelMotion in the graph of the widget to make it visible. More details on that is on the bottom of the ReadMe file

Okay, can I use your plugin using Blueprint?
And where do I start to understand how your functions interact? That is, if there is no tutorial for your plugin, then where can I start to learn it?
For example, there is documentation from Unity, UE, as well as a lot of tutorial videos, but I don't know where to go for a starting point for learning your plugin.

**Comment by stkrwork** [comment]
Yes the plugin is set up to be used in blueprint, the only thing that needs to be done is import the model3 file and then you can use it in your UMG widgets in combination with the image widget. More extensive documentation on it is still on my list to write, which was the plan to follow after i integrated the expressions support as well

**Comment by Soldream0** [comment]
Damn, I'll be waiting for your update with bated breath. God, I'm so glad you're doing this.

Firstly, will there be problems if I use the current version of your plugin, and when you release an updated version, I will update your plugin in my project?
Secondly, do you need any small help in writing your documentation? I would be happy to help. (besides money, I'm pretty poor)
